// Generated by CoffeeScript 1.7.1
(function() {
  var main, ts, wrapper;

  ts = require('ts3sq');

  wrapper = require('./server-wrapper');

  main = {
    start: function(config, _callback) {
      var client;
      client = new ts.ServerQuery(config.host, config.sqPort);
      wrapper = wrapper(client);
      return client.on('ready', function() {
        wrapper.execute(null, "login " + config.loginName + " " + config.loginPwd);
        wrapper.execute(null, "use port=" + config.sid, function(ret) {
          console.log(ret);
          return console.log('connected');
        });
        wrapper.execute(null, "clientupdate client_nickname=" + (wrapper.parseStr(config.displayName)), function(ret) {
          return console.log(ret);
        });
        wrapper.execute(null, "whoami", function(ret) {
          var ids;
          console.log("Test");
          ids = {};
          ids.client_id = ret.response[0].client_id;
          return wrapper.execute(null, 'channelfind pattern=Test', function(ret) {
            console.log(ret);
            ids.channelID = ret.response[0].cid;
            return wrapper.execute(null, "clientmove clid=" + ids.client_id + " cid=" + ids.channelID, function(ret) {
              return console.log(ret);
            });
          });
        });
        if (_callback != null) {
          _callback();
        }
        return client;
      });
    }
  };

  module.exports = main;

}).call(this);
